scala_library(
    name = "core",
    srcs = glob(["*.scala"]),
    deps = [
        "//order-system/src/main/scala/sample/orders/common",
        "//order-system/src/main/scala/sample/orders/dal",
    ],
    visibility = ["//visibility:public"]
)
