scala_library(
    name = "dal",
    srcs = glob(["*.scala"]),
    deps = [
        "@mysql__mysql_connector_java//jar",
        "//order-system/src/main/scala/sample/orders/common"
    ],
    visibility = ["//visibility:public"]
)
